src/Entity/LigneDeCmd.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LigneDeCmdRepository")
 */
class LigneDeCmd
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="smallint")
     */
    private $quantite;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Produit")
     * @ORM\JoinColumn(nullable=false)
     */
    private $produit;

    /**
     * LigneDeCmd constructor
     *
     * @param $quantite
     * @param $produit
     */
    public function __construct($quantite,$produit)
    {
        $this->quantite = $quantite;
        $this->produit = $produit;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getSousTotal()
    {
        return $this->quantite * $this->getProduit()->getPrix();
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): self
    {
        $this->produit = $produit;

        return $this;
    }

    public function __toString()
    {
        return $this->getProduit()->getNom();
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html class="no-js" lang="fr">
	<head>

		<meta charset="utf-8"/>
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<title>
			{% block title %}Welcome!
			{% endblock %}
		</title>
		{% block stylesheets %}
		<!-- Font Awesome CSS -->
    <script src="https://kit.fontawesome.com/ec63adeb54.js" crossorigin="anonymous"></script>
	
			<link rel="stylesheet" href="{{ asset('assets/css/app.css')}}">
				<link rel="stylesheet" href="{{ asset('assets/css/style.css')}}">
		{% endblock %}
	</head>
	<body>
		{% block body %}{% endblock %}
		{% block javascripts %}

			<script src="{{asset('assets/js/jquery.js')}}"></script>
			<script src="js/vendor/what-input.js"></script>
			<script src="{{asset('assets/js/app.js')}}"></script>
			<script>
				$(document).foundation();
			</script>
		{% endblock %}
	</body>
</html>

templates/default.html.twig
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Default</title>
	</head>
	<body>
		{% block body %}
			<h1>{{message}}</h1>
			<p>
				<a href="{{path("default_action")}}">vers action</a>
			</p>
		{% endblock %}
	</body>
</html>

templates/navbar.html.twig
<!-- LE COMPOSANT NAVBAR-->
<div class="grid-x">
	<div class="cell">
		<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
			<button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
			<div class="title-bar-title">Menu</div>
		</div>
		<div class="top-bar" id="responsive-menu">
			<div class="top-bar-left">
				<ul class="dropdown menu" data-dropdown-menu>
					<li class="menu-text">J4L-TECHNOLOGIES</li>
					<li>
						<a href="{{path('store_accueil')}}">Accueil</a>
					</li>
					 {% if is_granted("ROLE_ADMIN") %}
					<li class="has-submenu">
						<a href="{{path('enseigne_liste')}}">Enseigne</a>
						<ul class="submenu menu vertical" data-submenu>
							<li>
								<a href="{{path('enseigne_liste')}}">Liste</a>
							</li>
						</ul>
					</li>
					<li class="has-submenu">
						<a href="{{path('produit_liste')}}">Produit</a>
						<ul class="submenu menu vertical" data-submenu>
							<li>
								<a href="{{path('produit_liste')}}">Liste</a>
							</li>
						</ul>
					</li>
					<li class="has-submenu">
						<a href="#">User</a>
						<ul class="submenu menu vertical" data-submenu>
							<li>
								<a href="#">Liste</a>
							</li>
						</ul>
					</li>
						{% endif %}
				</ul>
			</div>

			<div class="top-bar-right">
				<ul class="dropdown menu" data-dropdown-menu>
					<li class="has-submenu">
						<a href="#" style="margin-right: 7rem">🛒 Panier</a>
						<ul class="submenu menu vertical" data-submenu>
							<table class="tabPanier hover">
								<thead>
									<tr>
										<th>Produit</th>
										<th>Quantité</th>
										<th>Sous total</th>
										<th>Actions</th>
									</tr>
								</thead>
								<tbody>
									{% for lc in lignesCmds %}
										<tr>
											<td>{{ lc.ligne_cmd }}</td>
											<td class="align-center">{{ lc.ligne_cmd.quantite }}</td>
											<td class="align-right">
												<strong>{{ lc.ligne_cmd.sousTotal }}</strong>
											</td>
											<td>
												<button>
                                                    <a href="{{path('panier_supprimer',{id: lc.ligne_cmd.produit.id })}}" class="panierActionSupprimer">
                                                </button>
													<strong>
														<i class="fas fa-trash-alt fa-lg">⛽</i>
													</strong>
												</a>
											</td>
										</tr>
									{% else %}
										<tr>
											<td colspan="4">Le panier est vide</td>
										</tr>
									{% endfor %}
									{% if total > 0 %}
										<tr class="total">
											<td colspan="2" class="text-right">
												<strong>TOTAL</strong>
											</td>
											<td class="text-right primary">
												<strong>{{ total }}</strong>
											</td>
											<td class="text-right primary"></td>
										</tr>
									{% endif %}
								</tbody>
							</table>
						</ul>
					</li>
				</ul>
			</div>

			<div class="top-bar-right">
				<ul class="dropdown menu" data-dropdown-menu>

                    {% if is_granted("ROLE_USER") %}

					<li class="has-submenu">
						<a href="{{path('app_mon_compte')}}" style="margin-right: 7rem">👨‍💻 Profile</a>
					</li>

			<ul class="submenu menu vertical" data-submenu>
					
					<li>
						<a href="{{path('app_logout')}}" style="margin-right: 7rem">Logout</a>
					</li>
					
				     {% else %}

					<li>
						<a href="{{path('app_login')}}" style="margin-right: 7rem">👨‍💻 Login</a>
					</li>

                     {% endif %}

			</ul>
					<div class="top-bar-right">
							<ul class="menu">
								<li>
							<input type="search" placeholder="Search"/>
								</li>
							<button type="button" class="button">Search</button>
							</ul>
					</div>
					
					
				</ul>
			</div>
		</div>
	</div>
</div>
<!-- FIN DU COMPOSANT NAVBAR-->

templates/titre.html.twig
<!--LE COMPOSANT TITRE -->
		<div class="grid-x"> <div class="cell text-center">
			<h1 class="titrePage">{{ titrePage}}</h1>
		</div>
	</div>
<!--FIN DU COMPOSANT TITRE -->